### ISSUE TITLE
Dagger2 and ButterKnife 8.0.1 cannot seem to coexist

### ISSUE THREAD

**Issue by kenshin171** [JakeWharton/butterknife#530]
My Dagger2 generated class does not seem to be generated when ButterKnife is on version 8.0.1. Reverting back to ButterKnife 7.0.1 solves the problem. Could this be a conflicting annotation processor with Dagger2?

Dagger2 version 2.2 with ButterKnife version 8.0 1 fails to build, i get a "cannot find symbol class \<some class name\> " error for my dagger2 classes.

Dagger2 version 2.2 with butterknife version 7.0.1 builds and runs fine.

Below are my configs for dagger2 and butterknife
```
compile "com.google.dagger:dagger:2.2"
apt "com.google.dagger:dagger-compiler:2.2"

compile "com.jakewharton:butterknife:8.0.1"
apt "com.jakewharton:butterknife-compiler:8.0.1"

provided "org.glassfish:javax.annotation:10.0-b28"
```

**Comment by gabrielittner** [comment]
It should work with Dagger 2.4 because that also uses JavaPoet 1.6.1.

**Comment by kenshin171** [comment]
Ahh! please close this issue. Completely my fault. My issue is similiar to #507 where my viewholder name for my RecyclerviewAdapter was starting with a smaller case letter thus breaking the annotations processor at build time.

**Comment by JakeWharton** [comment]
I'll try to fix that this week.
